"""Add password hash to users

Revision ID: 66843a7465f0
Revises: 69c4a91fe767
Create Date: 2026-09-04 15:15:55.255069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66843a7465f0'
down_revision: Union[str, Sequence[str], None] = '69c4a91fe767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column('password_hash', sa.String(), nullable=True)
    )

    op.execute(
        "UPDATE users SET password_hash = 'TEMPORARY_PASSWORD_HASH'"
    )

    op.alter_column(
        'users',
        'password_hash',
        existing_type=sa.String(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
