"""Add asset user foreign key

Revision ID: 69c4a91fe767
Revises: ce2e1f6c1e0d
Create Date: 2026-09-01 22:43:58.743874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c4a91fe767'
down_revision: Union[str, Sequence[str], None] = 'ce2e1f6c1e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
